### ISSUE TITLE
Does freedos define its own printf types?

### ISSUE THREAD

**Issue by andrewbird** [stsp/fdpp#15]
After getting `tn_printf()` in truename to print to dosemu I find that dosemu crashes. I find it's when a debug statement tries to print `%P` with `GET_FP32(cdsEntry)` as its arg. Strangely commenting it out also makes the DOS prompt look correct too.

What should the correct fix be, add `%P` to dosemu, or something else?

**Comment by stsp** [comment]
OK, lets keep this open in case you are
going to close this from the patch. :)

**Comment by andrewbird** [comment]
Mmm there are a few 
~~~
ajb@polly:/clients/common/fdpp.git$ git grep 'DebugPrintf.*%P'
kernel/config.c:    DebugPrintf(("Stacks allocated at %P\n", GET_FP32(stackBase)));
kernel/config.c:  DebugPrintf((" (%P)", GET_FP32(LoL->_firstbuf)));
kernel/dyninit.c:  DebugPrintf(("dynamic data end at %P\n",
~~~

Could I add what you suggest to the code in thunks.c so it's transparent?

**Comment by stsp** [comment]
Yes, that's what I meant.
Add that to thunks.c but don't alter
the public API.

**Comment by andrewbird** [comment]
Mmm, not sure how I can do this without either a FreeDOS `_vsprintf()` or gnu extension `__builtin_va_arg_pack()` any ideas?

**Comment by stsp** [comment]
> Mmm, not sure how I can do this without either a FreeDOS _vsprintf()

Yep, please add. :)
There is no intention to keep the original
sources unmodified, especially when adding
the functionality that was supposed to be there.

**Comment by stsp** [comment]
`_snprintf()` is also missing btw, only `_sprintf()`
is there. I used external `snprintf()` because of
the laziness. There should be all those `_snprintf()`,
`_vsprintf()`, `_vsnprintf()`.

**Comment by andrewbird** [comment]
I have the patch for `fdprintf()` in thunks should I do the same for `fdlogprintf()`?

**Comment by andrewbird** [comment]
I was thinking that it would be a lot simpler in thunks.cc if the fdpp -> dosemu interface just took a string to print, rather than format/va_args. Is there still a use case for having dosemu process the format and args?

**Comment by stsp** [comment]
The problem with this approack is that you
call from fdpp to freedos.
The basic considerations are:
- No calls from freedos to fdpp as freedos
should be able to leave his own life also w/o
and fdpp. The exceptions from this are `dosobj_init()`,
`RelocHook()` and (in asm) `plt_init`. You break
this part by providing a debug calls. It would be
better to have the debug calls ready, but not
really called in the code (ifdefed to something
like `DEBUG_PRINT_DOSEMU` as is currently
done for `DEBUG_PRINT_COMPORT`). But I
don't see a big reason even for this because
the debug goes to dosemu screen in either case,
so do you want to go it to dosemu log?
- Minimum calls from fdpp to dosemu to make
the life of future adopters (like freedos-32) easier.
- No calls from fdpp to freedos. Well, I have hard
times thinking up the good reason for this, except
that currently this is the case. :) You want to call
to those _vsprintf() funcs from fdpp, but why to
do this, if you can instead do it the other way around,
like currently is done in `init_fatal()` and `DynAlloc()`?

**Comment by stsp** [comment]
So if would be better to provide some function
in freedos, that will call either `_printf()` or
`_sprintf()`+`fdprintf()` depending on the debug
macros.
